apiVersion: v1
kind: Service
metadata:
  name: service-react-nginx-app-ilb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: react-nginx
spec:
  type: LoadBalancer
  selector:
    app: react-nginx
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
