# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-nginx
  template:
    metadata:
      labels:
        app: react-nginx
    spec:
      containers:
      - name: react-nginx-container
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/$PROJECT_ID/react-nginx:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
